/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
export interface WeatherForecast {
  date?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  temperatureC?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  temperatureF?: number | string;
  /** @nullable */
  summary?: string | null;
}
