/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { WeatherForecast } from "../backendV1.schemas";

export type getWeatherForecastResponse200TextPlain = {
  data: WeatherForecast[];
  status: 200;
};

export type getWeatherForecastResponse200ApplicationJson = {
  data: WeatherForecast[];
  status: 200;
};

export type getWeatherForecastResponse200TextJson = {
  data: WeatherForecast[];
  status: 200;
};

export type getWeatherForecastResponseSuccess = (
  | getWeatherForecastResponse200TextPlain
  | getWeatherForecastResponse200ApplicationJson
  | getWeatherForecastResponse200TextJson
) & {
  headers: Headers;
};
export type getWeatherForecastResponse = getWeatherForecastResponseSuccess;

export const getGetWeatherForecastUrl = () => {
  return `${import.meta.env.VITE_API_BASE_URL}/WeatherForecast`;
};

export const getWeatherForecast = async (
  options?: RequestInit,
): Promise<getWeatherForecastResponse> => {
  const res = await fetch(getGetWeatherForecastUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getWeatherForecastResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getWeatherForecastResponse;
};

export const getGetWeatherForecastQueryKey = () => {
  return [`${import.meta.env.VITE_API_BASE_URL}/WeatherForecast`] as const;
};

export const getGetWeatherForecastQueryOptions = <
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getWeatherForecast>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWeatherForecastQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWeatherForecast>>
  > = ({ signal }) => getWeatherForecast({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWeatherForecast>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWeatherForecastQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWeatherForecast>>
>;
export type GetWeatherForecastQueryError = unknown;

export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeatherForecast>>,
          TError,
          Awaited<ReturnType<typeof getWeatherForecast>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeatherForecast>>,
          TError,
          Awaited<ReturnType<typeof getWeatherForecast>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWeatherForecastQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
